my_string = input('введите строку: ')
print(len(my_string))
my_string = input()
print(my_string.upper())
my_string = input()
print(my_string.lower())
my_string = input()
print(my_string.replace(" ",""))
my_string = input()
print(my_string[0])
my_string = input()
print(my_string[-1])